"""
Маппинг имен иконок для совместимости со старыми именами иконок.
Переводит старые имена в формат Lucide Icons.
Извлечен из GopiAI-Widgets/gopiai/widgets/core/icon_adapter.py
"""

from typing import Optional

# Карта соответствия старых имен иконок новым именам Lucide
ICON_NAME_MAPPING = {
    # Общие иконки
    "home": "home",
    "settings": "settings",
    "folder": "folder",
    "file": "file",
    "folder_open": "folder-open",
    "terminal": "terminal",
    "code": "code",
    "text_file": "file-text",
    "refresh": "refresh-cw",
    "save": "save",
    "search": "search",
    "info": "info",
    "link": "link",
    "documentation": "book",
    "preferences": "settings",
    "browser": "globe",
    "run": "play",
    "close": "x",
    "emoji": "smile",
    "chat": "message-circle",
    "open": "folder-open",
    "python_file": "file-code",
    "markdown": "file-text",
    "flow": "git-branch",
    "debug": "bug",
    "app_icon": "cpu",
    "arrow_left": "arrow-left",
    "arrow_right": "arrow-right",
    "arrow_up": "arrow-up",
    "arrow_down": "arrow-down",
    "cut": "scissors",
    "copy": "copy",
    "paste": "clipboard",
    "play": "play",
    "arrow": "arrow-down",
    "close_black": "x",
    "close_white": "x",
    "maximize_black": "maximize",
    "maximize_white": "maximize",    "float_black": "box",
    "float_white": "box",
    "git": "git-branch",
    # Дополнительные маппинги для браузера
    "back": "chevron-left",
    "forward": "chevron-right",
    "stop": "x-circle",
    "analyze": "search-check",
    "view": "eye",
    "clear": "trash-2",
    # Дополнительные маппинги для типов файлов
    "js_file": "file-code",
    "html_file": "file-code",
    "css_file": "file-code",
    "json": "braces",
    "image_file": "image",
    "document": "file-text",
    "spreadsheet": "table",
    "pdf": "file-text",
    "archive": "archive",
    "home_folder": "home",
    "drive": "hard-drive",
    "agent": "bot",
    "tools": "tool",
    "console": "terminal",
    "inspect": "search",
    "message-square": "message-square",
    "check-circle": "check-circle",
    "file-plus": "file-plus",
    "save-all": "save-all",
    "grid": "grid",
    "palette": "palette",
    "file-code": "file-code",
    "undo": "undo",
    "redo": "redo",
    # Дополнительные иконки для различных UI компонентов
    "minimize": "minimize",
    "maximize": "maximize",
    "restore": "move",
    "dock": "layout",
    "pin": "pin",
    "unpin": "pin-off",
    "edit": "edit",
    "delete": "trash",
    "add": "plus",
    "remove": "minus",
    "check": "check",
    "x-circle": "x-circle",
    "alert": "alert-triangle",
    "warning": "alert-triangle",
    "error": "alert-octagon",    "float_black": "box",
    "float_white": "box",
    "git": "git-branch",
    # Дополнительные маппинги для браузера
    "back": "chevron-left",
    "forward": "chevron-right",
    "stop": "x-circle",
    "analyze": "search-check",
    "view": "eye",
    "clear": "trash-2",
    # Дополнительные маппинги для типов файлов
    "js_file": "file-code",
    "html_file": "file-code",
    "css_file": "file-code",
    "json": "braces",
    "image_file": "image",
    "document": "file-text",
    "spreadsheet": "table",
    "pdf": "file-text",
    "archive": "archive",
    "home_folder": "home",
    "drive": "hard-drive",
    "agent": "bot",
    "tools": "tool",
    "console": "terminal",
    "inspect": "search",
    "message-square": "message-square",
    "check-circle": "check-circle",
    "file-plus": "file-plus",
    "save-all": "save-all",
    "grid": "grid",
    "palette": "palette",
    "file-code": "file-code",
    "undo": "undo",
    "redo": "redo",
    # Дополнительные иконки для различных UI компонентов
    "minimize": "minimize",
    "maximize": "maximize",
    "restore": "move",
    "dock": "layout",
    "pin": "pin",
    "unpin": "pin-off",
    "edit": "edit",
    "delete": "trash",
    "add": "plus",
    "remove": "minus",
    "check": "check",    "x-circle": "x-circle",
    "alert": "alert-triangle",
    "warning": "alert-triangle",
    "error": "alert-octagon",
    "success": "check-circle",
    "info-circle": "info",
    "help": "help-circle",
    "settings-2": "settings-2",
    "user": "user",
    "logout": "log-out",
    "login": "log-in",
    "menu": "menu",
    "more": "more-horizontal",
    "more-vertical": "more-vertical",
    "send": "send",
    "upload": "upload",
    "download": "download",
    "camera": "camera",
    "mic": "mic",
    "mic-off": "mic-off",
    "video": "video",
    "video-off": "video-off",
    "speaker": "volume-2",
    "mute": "volume-x",
    "calendar": "calendar",
    "clock": "clock",
    "bell": "bell",
    "star": "star",
    "heart": "heart",
    "bookmark": "bookmark",
    "flag": "flag",
    "trash": "trash",
    "archive": "archive",
    "package": "package",
    "gift": "gift",
    "coffee": "coffee",
    "briefcase": "briefcase",
    "music": "music",
    "filter": "filter",
    "database": "database",
    "server": "server",
    "power": "power",
    "wifi": "wifi",
    "bluetooth": "bluetooth",
    "share": "share",
    "eye": "eye",
    "eye-off": "eye-off",
    "lock": "lock",
    "unlock": "unlock",    "key": "key",
    "hash": "hash",
    "at-sign": "at-sign",
    "cloud": "cloud",
    "layers": "layers",
    "list": "list",
    "grid-view": "grid",
    "list-view": "list",
    "shuffle": "shuffle",
    "repeat": "repeat",
    "crop": "crop",
    "rotate": "rotate-cw",
    "zoom-in": "zoom-in",
    "zoom-out": "zoom-out",
    "monitor": "monitor",
    "tablet": "tablet",
    "smartphone": "smartphone",
    "laptop": "laptop",
    "printer": "printer",
    "shopping-bag": "shopping-bag",
    "shopping-cart": "shopping-cart",
    "tag": "tag",
    "scissors": "scissors",
    "paperclip": "paperclip",
    "map": "map",
    "map-pin": "map-pin",
    "navigation": "navigation",
    "globe": "globe",
    "umbrella": "umbrella",
    "mail": "mail",
    "message": "message-circle",
    "phone": "phone",
    "signal": "signal",
    "battery": "battery",
    "headphones": "headphones",
    "trending-up": "trending-up",
    "trending-down": "trending-down",
    "bar-chart": "bar-chart",
    "pie-chart": "pie-chart",
    "line-chart": "line-chart",
    "activity": "activity",
    "disc": "disc",
    "droplet": "droplet",
    "credit-card": "credit-card",
    "anchor": "anchor",
    "award": "award",
    "zap": "zap",    # Дополнительные маппинги
    "plan_create": "plus",
    "plan-create": "plus",
    "plan_approve": "check",
    "plan-approve": "check",
    "plan_reject": "x",
    "plan-reject": "x",
    "execute": "play",
    "send": "send",
    "expand": "arrow-down",
    "collapse": "arrow-up",
    "refresh-cw": "refresh",
    "approve": "check",
    "reject": "x",
    "expand-all": "arrow-down",
    "collapse-all": "arrow-up",
    "save-session": "save",
    "new-plan": "plus",
    "plan": "git-branch",
    "history": "clock",
    "strategy": "activity",
    "create": "plus",
    "edit": "edit",
    "delete": "trash",      
    # Файловые операции
    "📦": "package",
    "📂": "folder",
    "📄": "file-text",
    "📝": "edit-3",
    "💾": "save",
    "📁": "folder-open",
    "🗂️": "folder-tree",

    # UI элементы
    "🔧": "settings",
    "⚙️": "cog",
    "🎨": "palette",
    "🌙": "moon",
    "☀️": "sun",
    "🔍": "search",
    "➕": "plus",
    "❌": "x",
    "✅": "check",
    "⚠️": "alert-triangle",
    "❗": "alert-circle",

    # Навигация
    "🏠": "home",
    "🔙": "arrow-left",
    "🔄": "refresh-cw",
    "📊": "bar-chart-3",
    "🎯": "target",
    "🚀": "rocket",

    # Системные
    "💻": "monitor",
    "🖥️": "pc",
    "📱": "smartphone",
    "🔌": "plug",
    "🌐": "globe",
    "📡": "wifi",

    # Статусы
    "🟢": "circle", # зеленый статус
    "🔴": "x-circle", # красный статус
    "🟡": "alert-circle", # желтый статус
    "🔵": "info", # синий статус
}


def get_lucide_name(icon_name: str) -> str:
    """
    Преобразование старого имени иконки в имя Lucide.
    
    Args:
        icon_name: Старое имя иконки
        
    Returns:
        str: Имя иконки в формате Lucide
    """
    # Если есть в маппинге, используем его
    if icon_name in ICON_NAME_MAPPING:
        return ICON_NAME_MAPPING[icon_name]
    
    # Если имя уже в формате Lucide (содержит дефисы), возвращаем как есть
    if "-" in icon_name:
        return icon_name
    
    # Иначе возвращаем исходное имя
    return icon_name


__all__ = ['ICON_NAME_MAPPING', 'get_lucide_name']
