"""
Pytest markers for known issues in GopiAI test suite.
Auto-generated by KnownIssuesManager - do not edit manually.
"""

import pytest

# Known issue markers

xfail_issue_TEST_001 = pytest.mark.xfail(
    reason="API timeout in authentication (Issue: TEST-001)",
    strict=False
)

xfail_issue_TEST_002 = pytest.mark.xfail(
    reason="UI widget rendering issue (Issue: TEST-002)",
    strict=False
)

xfail_issue_TEST_003 = pytest.mark.xfail(
    reason="Memory system indexing slow (Issue: TEST-003)",
    strict=False
)


# Register markers with pytest
def pytest_configure(config):
    """Register custom markers."""
    config.addinivalue_line("markers", "xfail_issue_TEST_001: API timeout in authentication")
    config.addinivalue_line("markers", "xfail_issue_TEST_002: UI widget rendering issue")
    config.addinivalue_line("markers", "xfail_issue_TEST_003: Memory system indexing slow")
