"""
Pytest markers for known issues in GopiAI codebase.
Auto-generated by problem discovery system.
"""

import pytest

# Known issue markers for expected failures


def mark_known_issues_GopiAI-CrewAI_tools_crewai_toolkit_tools_llamaindex_tool_llamaindex_tool():
    """Mark known issues for GopiAI-CrewAI_tools_crewai_toolkit_tools_llamaindex_tool_llamaindex_tool."""
    markers = []
    markers.append(pytest.mark.xfail(
        reason="TODO/FIXME comment: we are replacing the schema with our custom schema",
        strict=False
    ))
    return markers


def mark_known_issues_GopiAI-UI_gopiai_ui_components_chat_widget():
    """Mark known issues for GopiAI-UI_gopiai_ui_components_chat_widget."""
    markers = []
    markers.append(pytest.mark.xfail(
        reason="TODO/FIXME comment: Реализовать применение темы",
        strict=False
    ))
    return markers


def mark_known_issues_GopiAI-UI_gopiai_ui_components_unified_model_widget():
    """Mark known issues for GopiAI-UI_gopiai_ui_components_unified_model_widget."""
    markers = []
    markers.append(pytest.mark.xfail(
        reason="TODO/FIXME comment: Реализовать тест соединения",
        strict=False
    ))
    markers.append(pytest.mark.xfail(
        reason="TODO/FIXME comment: Реализовать сброс конфигурации",
        strict=False
    ))
    return markers
